tpd:
  peer1Port: 25001
  peer2Port: 25002
 
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
---
spring:
  application:
    name: eureka-peer1
  profiles: eureka-peer1
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:${tpd.peer2Port}/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${tpd.peer1Port}
 
---
---
spring:
  application:
    name: eureka-peer2
  profiles: eureka-peer2
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:${tpd.peer1Port}/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${tpd.peer2Port}
